### ISSUE TITLE
复制粘贴，复制的文本会一次性出现两次

### ISSUE THREAD

**Issue by cynl7** [mirror29/wangEditor-formula#1]
1.源码下载后npm install
2.npm run serve
3.富文本内复制选中内容，粘贴一次性出现两个选中的复制内容

**Comment by mirror29** [comment]
将 tryChangeActive () 函数注释取消即可，最新提交已修复

**Comment by mirror29** [comment]
> 1.源码下载后npm install
> 2.npm run serve
> 3.富文本内复制选中内容，粘贴一次性出现两个选中的复制内容

将 tryChangeActive () 函数注释取消即可，最新提交已修复

**Comment by cynl7** [comment]
好的，问题已解决，谢谢
